apiVersion: v1
kind: Pod
metadata:
  name: my-app-pod
spec:
  containers:
  - name: redis
    image: redis:latest
    ports:
    - containerPort: 6379
    volumeMounts:
    - name: data
      mountPath: /data
  - name: rails
    image: my-rails-app:latest
    ports:
    - containerPort: 3000
    env:
    - name: REDIS_URL
      value: redis://redis:6379/0
    volumeMounts:
    - name: data
      mountPath: /data
  volumes:
  - name: data
    emptyDir: {}
